spring.application.name=spring-payment-processor

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka-0.kafka-headless:9092,kafka-1.kafka-headless:9092,kafka-2.kafka-headless:9092}
spring.kafka.consumer.group-id=payment-processor-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.isolation-level=read_committed
spring.kafka.consumer.max-poll-records=10
spring.kafka.listener.ack-mode=manual_immediate

spring.kafka.producer.acks=all
spring.kafka.producer.retries=2147483647
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
spring.kafka.producer.properties.linger.ms=5
spring.kafka.producer.properties.compression.type=lz4

# Lab env vars: ORDER_TOPIC, PAYMENT_SUCCESS_TOPIC, PAYMENT_FAILED_TOPIC
app.topics.payment-init=${ORDER_TOPIC:payment-init}
app.topics.order=${PAYMENT_SUCCESS_TOPIC:order-created}
app.topics.payment-failed=${PAYMENT_FAILED_TOPIC:order-cancelled}
app.topics.inventory=inventory
app.order-service.url=http://spring-order-service:8081
